### ISSUE TITLE
How deploy to Heroku?

### ISSUE THREAD

**Issue by MemeGiver** [titaniumnetwork-dev/Donglalu-Proxy-The-Second-Coming#4]
Help

**Comment by truubo** [comment]
You dont

**Comment by MemeGiver** [comment]
> 

Fuck yourself

**Comment by truubo** [comment]
Kill yourself

**Comment by MemeGiver** [comment]
IM DELETING YOU DADDY!

IM DELETING YOU, DADDY!😭👋 ██]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]] 10% complete..... ████]]]]]]]]]]]]]]]]]]]]]]]]]]] 35% complete.... ███████]]]]]]]]]]]]]]]] 60% complete.... ███████████] 99% complete..... 🚫ERROR!🚫 💯True💯 Daddies are irreplaceable 💖I could never delete you Daddy!💖 Send this to ten other 👪Daddies👪 who give you 💦cummies💦 Or never get called ☁️squishy☁️ again❌❌😬😬❌❌ If you get 0 Back: no cummies for you 🚫🚫👿 3 back: you're squishy☁️💦 5 back: you're daddy's kitten😽👼💦 10+ back: Daddy😛😛💕💕💦👅👅
